version: '3.7'

services:
  api:
    image: lucaxue/booksapi:1.0
    container_name: books_api
    build:
      context: .
      dockerfile: Dockerfile.aspnet
    ports:
      - '5000:5000'
    depends_on:
      - database
    networks:
      - backend
    volumes:
      - './:/app/'
    env_file:
      - ./src/.env

  database:
    image: lucaxue/booksdb:1.0
    container_name: books_db
    build:
      context: .
      dockerfile: Dockerfile.postgre
    networks:
      - backend
    env_file:
      - ./src/.env

networks:
  backend:
    driver: bridge
